algoritmo "semnome"
// Função :
// Autor :
// Data : 19/05/2013
// Seção de Declarações 

arquivo "C:\Users\Athauan Marques\Desktop\lista de exercicios 5\produto2.txt"

var
 CODPROD: caracter
 QTDMI, QTDMAX, QTDEST: inteiro
inicio
// Seção de Comando
Escreval ("----------------------------------")
Escreval ("Digite o Codigo do produto")
Escreval ("----------------------------------")
leia (CODPROD)
Escreval ("----------------------------------")
Escreval ("Digite a Quantidade Minima")
Escreval ("----------------------------------")
leia (QTDMI)
Escreval ("----------------------------------")
Escreval ("Digite a Quantidade Maxima")
Escreval ("----------------------------------")
leia (QTDMAX)
Escreval ("----------------------------------")
Escreval ("Digite a Quantidade de Estoque")
Escreval ("----------------------------------")
leia (QTDEST)
fimalgoritmo
