algoritmo "semnome"
// Função :
// Autor :
// Data : 25/06/2013
// Seção de Declarações 
var
n1, n2, n3, n4: inteiro
soma, r1, r2, r3, r4: real

inicio
escreva (" informe numero 1 :")
leia (n1)

escreva (" informe numero 2 :")
leia (n2)

escreva (" informe numero 3 :")
leia (n3)

escreva (" informe numero 4 :")
leia (n4)

r1 <- (n1*n1)
r2 <- (n2*n2)
r3 <- (n3*n3)
r4 <- (n4*n4)

soma <- (r1+r2+r3+r4)

escreval ("resultado da som é: ", soma)

fimalgoritmo
