algoritmo "semnome"
// Função :
// Autor :
// Data : 25/06/2013
// Seção de Declarações 
var
result, valorDolares, cotacao: real

inicio

escreval ("Informe a cotação do dolar: ")
leia (cotacao)

escreval ("informe o valor do dolar: ")
leia (valorDolares)

result <- valorDolares/cotacao

escreval ("A conversão dolar para real é de: ", result, " R$")

//para converte Real em Dolar ....
//Vc pega o valor em Real e divide pelo cambio em Real ai tera o valor em Dolar

fimalgoritmo
