algoritmo "semnome"

var
   ind:real
inicio
   Escreva("Informe o índice de poluição")
   Leia(ind)
   
   Se ind>=0.26 Entao
      Se ind<=0.30 Entao
      Escreval("Grupo 1 INTERROMPA SUAS ATIVIDADES")
      fimse
   fimse
   
   se ind>=0.31 Entao
      se ind<=0.40 Entao
      Escreval ("Grupo 1 e Grupo 2 INTERROMPAM SUAS ATIVIDADES")
      fimse
   fimse
   
   Se ind>=0.41 Entao
   Escreval ("TODOS os grupos INTERROMPAM SUAS ATIVIDADES")
   fimse
   
fimalgoritmo
