algoritmo "Exercício 1 da Lista 2"
//Função: Medir poluição e Notificar
var
   ind:real
inicio
   Escreva("Informe o índice de poluição")
   Leia(ind)
   
   Se ind>=0.26 Entao
   escreval("Grupo 1 suspenda as Atividades")
   fimse
   Se ind>=0.31 Entao
   escreval("Grupo 2 suspenda as Atividades")
   fimse
   Se ind>=0.41 Entao
   escreval("Grupo 3 suspenda as Atividades")
   fimse
   
fimalgoritmo
