-- Banco de dados de filmes. 

DROP DATABASE IF EXISTS filmes_db;
CREATE DATABASE filmes_db ;
USE filmes_db;


-- create tables
CREATE TABLE IF NOT EXISTS Filme
(   filmeid	INTEGER               	NOT NULL,
    titulo   	VARCHAR(70)     	NOT NULL,
    ano    	INTEGER              	NOT NULL,
    nota	DECIMAL(4,2)        	NULL,
    votos  	INTEGER                	NULL,
    PRIMARY KEY (filmeid)
);
CREATE TABLE IF NOT EXISTS Ator
(   atorid		INTEGER                NOT NULL,
    nome    	VARCHAR(35)     NOT NULL,
    PRIMARY KEY (atorid)
);
CREATE TABLE IF NOT EXISTS Elenco
(   filmeid	INTEGER                NOT NULL,
    atorid	INTEGER                NOT NULL,
    ordem	INTEGER                NULL,
    PRIMARY KEY (filmeid, atorid)
);
-- referential constraints
ALTER TABLE Elenco
    ADD CONSTRAINT fk_Filme_Elenco_filmeid FOREIGN KEY  (filmeid) 
    REFERENCES Filme (filmeid);
ALTER TABLE Elenco
    ADD CONSTRAINT fk_Filme_Elenco_atorid FOREIGN KEY  (atorid) 
       REFERENCES ator (atorid);

-- inserts
INSERT INTO filme VALUES (1,'Star Wars',1977,8.9,14182);
INSERT INTO filme VALUES (2,'Pulp Fiction',1994,8.4,11693);
INSERT INTO filme VALUES (3,'Blade Runner',1982,8.6,8665);
INSERT INTO filme VALUES (4,'Titanic',1997,9.2,8129);
INSERT INTO filme VALUES (5,'Braveheart',1995,8.4,8074);
INSERT INTO filme VALUES (6,'Empire Strikes Back, The',1980,8.5,8050);
INSERT INTO filme VALUES (7,'Shawshank Redemption, The',1994,8.8,7850);
INSERT INTO filme VALUES (8,'Independence Day',1996,7.0,7138);
INSERT INTO filme VALUES (9,'Usual Suspects, The',1995,8.7,6981);
INSERT INTO filme VALUES (10,'Raiders of the Lost Ark',1981,8.4,6488);
INSERT INTO filme VALUES (11,'2001: A Space Odyssey',1968,8.4,6413);
INSERT INTO filme VALUES (12,'Forrest Gump',1994,7.8,6269);
INSERT INTO filme VALUES (13,'Aliens',1986,8.3,5811);
INSERT INTO filme VALUES (14,'Silence of the Lambs, The',1991,8.3,5715);
INSERT INTO filme VALUES (15,'Princess Bride, The',1987,8.4,5522);
INSERT INTO filme VALUES (16,'Terminator 2: Judgment Day',1991,8.0,5513);
INSERT INTO filme VALUES (17,'Casablanca',1942,8.7,5489);
INSERT INTO filme VALUES (18,'Monty Python and the Holy Grail',1974,8.4,5319);
INSERT INTO filme VALUES (19,'Star Trek: First Contact',1996,8.2,5298);
INSERT INTO filme VALUES (20,'Fargo',1996,8.2,5293);
INSERT INTO filme VALUES (21,'Twelve Monkeys',1995,8.0,5287);
INSERT INTO filme VALUES (22,'Trainspotting',1996,8.1,5233);
INSERT INTO filme VALUES (23,'Godfather, The',1972,8.7,5211);
INSERT INTO filme VALUES (24,'Se7en',1995,8.1,5107);
INSERT INTO filme VALUES (25,'Back to the Future',1985,7.8,5103);
INSERT INTO filme VALUES (26,'Rock, The',1996,8.0,4938);
INSERT INTO filme VALUES (27,'Reservoir Dogs',1992,8.3,4861);
INSERT INTO filme VALUES (28,'Apocalypse Now',1979,8.3,4860);
INSERT INTO filme VALUES (29,'Alien',1979,8.2,4828);
INSERT INTO filme VALUES (30,'Apollo 13',1995,7.8,4778);
INSERT INTO filme VALUES (31,'Clockwork Orange, A',1971,8.4,4767);
INSERT INTO filme VALUES (32,'JurassPark',1993,7.4,4707);
INSERT INTO filme VALUES (33,'English Patient, The',1996,8.1,4689);
INSERT INTO filme VALUES (34,'One Flew Over the Cuckoo''s Nest',1975,8.5,4545);
INSERT INTO filme VALUES (35,'Dr. Strangelove or: How I Learned to Stop Worrying and Love the Bomb',1963,8.6,4451);
INSERT INTO filme VALUES (39,'Terminator, The',1984,7.8,4225);
INSERT INTO filme VALUES (48,'True Lies',1994,7.3,3601);
INSERT INTO filme VALUES (94,'Total Recall',1990,7.1,2305);
INSERT INTO filme VALUES (180,'Predator',1987,7.2,1604);
INSERT INTO filme VALUES (263,'Conan the Barbarian',1981,6.9,1271);
INSERT INTO filme VALUES (321,'Twins',1988,6.3,1126);
INSERT INTO filme VALUES (334,'Last Action Hero',1993,5.9,1107);
INSERT INTO filme VALUES (410,'Dave',1993,7.4,962);
INSERT INTO filme VALUES (440,'Kindergarten Cop',1990,6.2,894);
INSERT INTO filme VALUES (471,'Running Man, The',1987,6.3,856);
INSERT INTO filme VALUES (629,'Commando',1985,6.1,673);
INSERT INTO filme VALUES (746,'Conan the Destroyer',1984,5.4,2);
INSERT INTO filme VALUES (932,'Red Heat',1988,5.8,402);
INSERT INTO filme VALUES (960,'Terminator 2: 3-D',1996,8.7,384);
INSERT INTO filme VALUES (1106,'Junior',1994,5.9,329);
INSERT INTO filme VALUES (1339,'Jingle All the Way',1996,6.0,262);
INSERT INTO filme VALUES (1551,'Raw Deal',1986,5.0,215);
INSERT INTO filme VALUES (1622,'Batman and Robin',1997,3.9,1925);
INSERT INTO filme VALUES (1644,'Red Sonja',1985,4.6,404);
INSERT INTO filme VALUES (1353,'Outrageous Fortune',1987,6.1,258);
INSERT INTO filme VALUES (975,'Night Shift',1982,6.6,377);
INSERT INTO filme VALUES (910,'Brady Bunch filme, The',1995,6.3,412);
INSERT INTO filme VALUES (793,'Money Pit, The',1986,5.8,482);
INSERT INTO ator VALUES (7975,'Shelley Long');
INSERT INTO ator VALUES (197,'Alice Krige');
INSERT INTO ator VALUES (7130,'Rebecca Jane Klingler');
INSERT INTO ator VALUES (8103,'Stephen Baldwin');
INSERT INTO ator VALUES (5511,'Madeleine Lebeau');
INSERT INTO ator VALUES (7051,'Ralph Peduto');
INSERT INTO ator VALUes(5512,'Madeleine Stowe');
INSERT INTO ator VALUES (5350,'Lisa Gay Hamilton');
INSERT INTO ator VALUES (8105,'Stephen Bridgewater');
INSERT INTO ator VALUES (5351,'Lisa Jakub');
INSERT INTO ator VALUES (3731,'James Lancaster');
INSERT INTO ator VALUES (5514,'Madge Ryan');
INSERT INTO ator VALUES (5190,'LeVar Burton');
INSERT INTO ator VALUES (4461,'John Murtagh');
INSERT INTO ator VALUES (1950,'David Steen');
INSERT INTO ator VALUES (8026,'Simonetta Stefanelli');
INSERT INTO ator VALUES (5191,'Lea Thompson');
INSERT INTO ator VALUES (4462,'John Nathan');
INSERT INTO ator VALUES (3490,'Ingrid Bergman');
INSERT INTO ator VALUES (2842,'G.D. Spradlin');
INSERT INTO ator VALUES (2761,'Frank Novak');
INSERT INTO ator VALUES (8028,'Siobhan Fallon');
INSERT INTO ator VALUES (6084,'Michael Madsen');
INSERT INTO ator VALUES (7219,'Richard Bright');
INSERT INTO ator VALUES (4708,'Julia Sweeney');
INSERT INTO ator VALUES (2845,'Gabriel Byrne');
INSERT INTO ator VALUES (2764,'Frank Oz');
INSERT INTO ator VALUES (6087,'Michael Massee');
INSERT INTO ator VALUES (1875,'David Early');
INSERT INTO ator VALUES (2848,'Gabriel Jarret');
INSERT INTO ator VALUES (2769,'Frank Seals Jr.');
INSERT INTO ator VALUES (440,'Anthony ''Chip'' Brienza');
INSERT INTO ator VALUES (445,'Anthony Chinn');
INSERT INTO ator VALUES (446,'Anthony Clark');
INSERT INTO ator VALUES (447,'Anthony Crivello');
INSERT INTO ator VALUES (448,'Anthony Daniels');
INSERT INTO ator VALUES (7141,'Reg E. Cathey');
INSERT INTO ator VALUES (7060,'Rance Howard');
INSERT INTO ator VALUES (4630,'Joseph Mazzello');
INSERT INTO ator VALUES (9005,'William Duell');
INSERT INTO ator VALUES (5441,'Louis Lombardi');
INSERT INTO ator VALUES (4631,'Joseph McKenna');
INSERT INTO ator VALUES (2930,'Gene Borkan');
INSERT INTO ator VALUES (5361,'Lisa Talerico');
INSERT INTO ator VALUES (4714,'Julian Glover');
INSERT INTO ator VALUES (4633,'Joseph Patrick Kelly');
INSERT INTO ator VALUES (3580,'Jack Conley');
INSERT INTO ator VALUES (8036,'Slim kens');
INSERT INTO ator VALUES (6254,'Mirron E. Willis');
INSERT INTO ator VALUES (5525,'Mae Whitman');
INSERT INTO ator VALUES (3581,'Jack Creley');
INSERT INTO ator VALUES (1880,'David Gant');
INSERT INTO ator VALUES (9009,'William Forsythe');
INSERT INTO ator VALUES (5445,'Louisa  Marie (I)');
INSERT INTO ator VALUES (5446,'Louisa Moritz');
INSERT INTO ator VALUES (5284,'Leslie Schofield');
INSERT INTO ator VALUES (4636,'Joseph Ragno');
INSERT INTO ator VALUES (5447,'Louise Fletcher');
INSERT INTO ator VALUES (5285,'Levani');
INSERT INTO ator VALUES (6179,'Miguel  Sandoval (I)');
INSERT INTO ator VALUES (3668,'James  Keane (I)');
INSERT INTO ator VALUES (2778,'Frank Whaley');
INSERT INTO ator VALUES (612,'Barry Dennen');
INSERT INTO ator VALUES (1889,'David Harold Brown');
INSERT INTO ator VALUES (290,'Andre B. Blake');
INSERT INTO ator VALUES (618,'Barry McGovern');
INSERT INTO ator VALUES (456,'Anthony Guidera');
INSERT INTO ator VALUES (457,'Anthony Heald');
INSERT INTO ator VALues (458,'Anthony Higgins');
INSERT INTO ator VALUES (459,'Anthony Hopkins');
INSERT INTO ator VALUES (6501,'Norwich Duff');
INSERT INTO ator VALUES (5610,'Margaret Colin');
INSERT INTO ator VALUES (4720,'Julian Wadham');
INSERT INTO ator VALUES (9014,'William H. Macy');
INSERT INTO ator VALUES (4803,'Karl Warren');
INSERT INTO ator VALUES (3832,'Jason Barry');
INSERT INTO ator VALUES (9017,'William Hootkins');
INSERT INTO ator VALUES (4562,'Jon Matthews');
INSERT INTO ator VALUES (2780,'Frankie Faison');
INSERT INTO ator VALUES (9018,'William Hope');
INSERT INTO ator VALUES (5535,'Maia Brewton');
INSERT INTO ator VALUES (4725,'Julie Araskog');
INSERT INTO ator VALUES (4482,'John Qualen');
INSERT INTO ator VALUES (3915,'Jeannie Linero');
INSERT INTO ator VALUES (6508,'Obba Babatund%');
INSERT INTO ator VALUES (4483,'John R. Woodward');
INSERT INTO ator VALUES (3754,'James Rebhorn');
INSERT INTO ator VALUES (7076,'Randy Oglesby');
INSERT INTO ator VALUES (5618,'Margaret Tyzack');
INSERT INTO ator VALUES (5537,'Majel Barrett');
INSERT INTO ator VALUES (5375,'Lloyd L. Tolbert');
INSERT INTO ator VALUES (4808,'Kasi Lemmons');
INSERT INTO ator VALUES (3836,'Jason Hervey');
INSERT INTO ator VALUES (2864,'Garrick Hagon');
INSERT INTO ator VALUES (6349,'Nathan George');
INSERT INTO ator VALUES (5296,'Lexie Bigham');
INSERT INTO ator VALUES (4567,'Jon Seda');
INSERT INTO ator VALUES (4486,'John Ratzenberger');
INSERT INTO ator VALUES (3757,'James Ritz');
INSERT INTO ator VALUES (3676,'James B. Howard');
INSERT INTO ator VALUES (7079,'Randy Quaid');
INSERT INTO ator VALUES (4487,'John Rhys-Davies');
INSERT INTO ator VALUES (1976,'DeVaughn Nixon');
INSERT INTO ator VALUES (1977,'Dean Cundey');
INSERT INTO ator VALUES (5299,'Liam Carney');
INSERT INTO ator VALUES (703,'Bert  Williams (II)');
INSERT INTO ator VALUES (545,'Arthur Senzy');
INSERT INTO ator VALUES (8131,'Stephen Wesley Bridgewater');
INSERT INTO ator VALUES (5540,'Mal Whyte');
INSERT INTO ator VALUES (8133,'Sterling Hayde');
INSERT INTO ator VALUES (5703,'Mark Hamill');
INSERT INTO ator VALUES (7081,'Raphael Sbarge');
INSERT INTO ator VALUES (3841,'Jason Marin');
INSERT INTO ator VALUES (5624,'Margery Mason');
INSERT INTO ator VALUES (4733,'Julie Donatt');
INSERT INTO ator VALUES (5544,'Malcolm McDowell');
INSERT INTO ator VALUES (4734,'Julie H. Morgan');
INSERT INTO ator VALUES (3682,'James Caan');
INSERT INTO ator VALUES (1981,'Dean Norris');
INSERT INTO ator VALUES (9029,'William Masson');
INSERT INTO ator VALUES (6437,'Nicolas Cage');
INSERT INTO ator VALUES (2954,'Geoffrey Blake');
INSERT INTO ator VALUES (8139,'Steve  Park (I)');
INSERT INTO ator VALUES (6357,'Neal McDonough');
INSERT INTO ator VALUES (5547,'Malcolm Storry');
INSERT INTO ator VALUES (5548,'Malcolm Tierney');
INSERT INTO ator VALUES (4819,'Kate Winslet');
INSERT INTO ator VALUES (3767,'James Tolkan');
INSERT INTO ator VALUES (4578,'Jonathan Frakes');
INSERT INTO ator VALUES (4497,'John Savident');
INSERT INTO ator VALUES (3687,'Jameaviezel');
INSERT INTO ator VALUES (712,'Betsy Brantley');
INSERT INTO ator VALUES (555,'Aubrey Morris');
INSERT INTO ator VALUES (478,'Anthony Sharp');
INSERT INTO ator VALUES (6520,'Oliver Maguire');
INSERT INTO ator VALUES (7251,'Richard Graham');
INSERT INTO ator VALUES (6360,'Ned Bellamy');
INSERT INTO ator VALUES (5551,'Mandy Patinkin');
INSERT INTO ator VALUES (4904,'Ken Daly');
INSERT INTO ator VALUES (4580,'Jonathan Hyde');
INSERT INTO ator VALUES (3932,'Jeff Goldblum');
INSERT INTO ator VALUES (4662,'Josip Elic');
INSERT INTO ator VALUES (7336,'Rick Warner');
INSERT INTO ator VALUES (6364,'Ned Vaughn');
INSERT INTO ator VALUES (4906,'Ken Gibbel');
INSERT INTO ator VALUES (3772,'James Whitmore');
INSERT INTO ator VALUES (3691,'James Cosmo');
INSERT INTO ator VALUES (5717,'Mark Matheisen');
INSERT INTO ator VALUES (3854,'Jay Acovone');
INSERT INTO ator VALUES (8229,'Stuart Rudin');
INSERT INTO ator VALUES (8148,'Steve Buscemi');
INSERT INTO ator VALUES (7095,'Ray Hassett');
insert INTO ator VALUES (5395,'Loren Dean');
INSERT INTO ator VALUES (6287,'Morgan Freeman');
INSERT INTO ator VALUES (5639,'Maria de Medeiros');
INSERT INTO ator VALUES (4748,'Juliette Binoche');
INSERT INTO ator VALUES (3695,'James Cromwell');
INSERT INTO ator VALUES (3777,'Jamie Abbott');
INSERT INTO ator VALUES (800,'Bill Smitrovich');
INSERT INTO ator VALUES (6289,'Morgan Paull');
INSERT INTO ator VALUES (3698,'James Deeth');
INSERT INTO ator VALUES (2969,'George  Harris (II)');
INSERT INTO ator VALUES (643,'Bee Duffell');
INSERT INTO ator VALUES (565,'Austin O''Brien');
INSERT INTO ator VALUES (9040,'William Redfield');
INSERT INTO ator VALUES (7502,'Robert Ruth');
INSERT INTO ator VALUES (9043,'William Sadler');
INSERT INTO ator VALUES (7180,'Ricco Ross');
INSERT INTO ator VALUES (4831,'Kathleen Quinlan');
INSERT INTO ator VALUES (9044,'William Sanderson');
INSERT INTO ator VALUES (6371,'Neil Giuntoli');
INSERT INTO ator VALUES (5804,'Mary Kate Schellhardt');
INSERT INTO ator VALUES (3,'Mark Rolston');
INSERT INTO ator VALUES (4913,'Ken Kells');
INSERT INTO ator VALUES (3941,'Jeff O''Haco');
INSERT INTO ator VALUES (8154,'Steve Giannelli');
INSERT INTO ator VALUES (6453,'Nikki Cox');
INSERT INTO ator VALUES (6291,'Morgana King');
INSERT INTO ator VALUES (2970,'George  Kelly (II)');
INSERT INTO ator VALUES (7183,'Rich Turner');
INSERT INTO ator VALUES (6373,'Neil Innes');
INSERT INTO ator VALUES (4672,'Juan A. Riojas');
INSERT INTO ator VALUES (7265,'Richard Kiley');
INSERT INTO ator VALUES (8319,'Talia Shire');
INSERT INTO ator VALUES (4593,'Jonny Lee Miller');
INSERT INTO ator VALUES (6376,'Neil Summers');
INSERT INTO ator VALUES (4594,'Jophery C. Brown');
INSERT INTO ator VALUES (2974,'George ''Buck'' Flower');
INSERT INTO ator VALUES (7268,'Richard L. Duran');
INSERT INTO ator VALUES (4919,'Ken Magee');
INSERT INTO ator VALUES (6297,'Morton Kondracke');
INSERT INTO ator VALUES (4677,'Judd Hirsch');
INSERT INTO ator VALUES (5488,'Lyman Ward');
INSERT INTO ator VALUES (2979,'George C. Scott');
INSERT INTO ator VALUES (2899,'Gary Houston');
INSERT INTO ator VALUES (653,'Ben Bode');
INSERT INTO ator VALUES (576,'B.D. Wong');
INSERT INTO ator VALUES (8322,'Tam White');
INSERT INTO ator VALUES (6702,'Paul Calderon');
INSERT INTO ator VALUES (5811,'Mary McDonnell');
INSERT INTO ator VALUES (7432,'Robert Duvall');
INSERT INTO ator VALUES (7270,'Richard Le Parmentier');
INSERT INTO ator VALUES (5731,'Mark Wheeler');
INSERT INTO ator VALUES (4840,'Kathryn Mullen');
INSERT INTO ator VALUES (7271,'Richard Leaf');
INSERT INTO ator VALUES (5570,'Marc Coppola');
INSERT INTO ator VALUES (6381,'Nelson Mashita');
INSERT INTO ator VALUES (4680,'Jude Ciccolella');
INSERT INTO ator VALUES (5734,'Marla Sucharetza');
INSERT INTO ator VALUES (3952,'Jeffrey DeMunn');
INSERT INTO ator VALUES (3791,'Jana Marie Hupp');
INSERT INTO ator VALUES (6627,'Patrick  Magee (I)');
INSERT INTO ator VALUES (4845,'Kathy Bates');
INSERT INTO ator VALUES (5575,'Marc McClure');
INSERT INTo ator VALUES (4846,'Kathy Griffin');
INSERT INTO ator VALUES (6467,'Noel Evangelisti');
INSERT INTO ator VALUES (5739,'Marlon Brando');
INSERT INTO ator VALUES (5658,'Marina Sirtis');
INSERT INTO ator VALUES (2985,'George Christy');
INSERT INTO ator VALUES (823,'Billy Crystal');
INSERT INTO ator VALUES (663,'Ben Marley');
INSERT INTO ator VALUES (745,'Bill  Raymond (I)');
INSERT INTO ator VALUES (826,'Billy Dee Williams');
INSERT INTO ator VALUES (827,'Billy Devlin');
INSERT INTO ator VALUES (7600,'Ron  Rondell (II)');
INSERT INTO ator VALUES (9060,'Willie Garson');
INSERT INTO ator VALUES (7603,'Ron  Young (I)');
INSERT INTO ator VALUES (7522,'Robert Winley');
INSERT INTO ator VALUES (9062,'Willoughby Gray');
INSERT INTO ator VALUES (8414,'Thom Barry');
INSERT INTO ator VALUES (6390,'Niall O''Brien');
INSERT INTO ator VALUES (5823,'Marya Small');
INSERT INTO ator VALUES (8173,'Steve Rankin');
INSERT INTO ator VALUES (7444,'Robert Haley');
INSERT INTO ator VALUES (5905,'Meadow Williams');
INSERT INTO ator VALUES (7283,'Richard Oldfield');
INSERT INTO ator VALUES (2990,'George DiCenzo');
INSERT INTO ator VALUES (8418,'Thomas  Crawford (I)');
INSERT INTO ator VALUES (8175,'Steve Reevis');
INSERT INTO ator VALUES (7285,'Richard Portnow');
INSERT INTO ator VALUES (6394,'Nicholas Cascone');
INSERT INTO ator VALUES (5746,'Marshall R. Teague');
INSERT INTO ator VALUES (4936,'Kenneth Colley');
INSERT INTO ator VALUES (9069,'Wolf Kahler');
INSERT INTO ator VALUES (4857,'Keenan Wynn');
INSERT INTO ator VALUES (4859,'Keir Dullea');
INSERT INTO ator VALUES (3968,'Jenette Goldstein');
INSERT INTO ator VALUES (750,'Bill Bolender');
INSERT INTO ator VALUES (912,'Bokeem Woodbine');
INSERT INTO ator VALUES (671,'Benicio Del Toro');
INSERT INTO ator VALUES (590,'Barbara Coles');
INSERT INTO ator VALUES (838,'Billy Zane');
INSERT INTO ator VALUES (7612,'Ron Donachie');
INSERT INTO ator VALUES (6721,'Paul Henreid');
INSERT INTO ator VALUES (4860,'Keith  Allen (I)');
INSERT INTO ator VALUES (3122,'Robert J. Stephenson');
INSERT INTO ator VALUES (7291,'Richard Roundtree');
INSERT INTO ator VALUES (8426,'Thomas F. Duffy');
INSERT INTO ator VALUES (6482,'Norman Alden');
INSERT INTO ator VALUES (8427,'Thomas F. Wilson');
INSERT INTO ator VALUES (6645,'Patrick McGoohan');
INSERT INTO ator VALUES (4782,'Karen Allen');
INSERT INTO ator VALUES (7294,'Richard Schiff');
INSERT INTO ator VALUES (8348,'Ted Grossman');
INSERT INTO ator VALUES (8186,'Steven  Wright (I)');
INSERT INTO ator VALUES (6809,'Pete Postlethwaite');
INSERT INTO ator VALUES (8188,'Steven Berkoff');
INSERT INTO ator VALUES (7297,'Richard Speight Jr.');
INSERT INTO ator VALUES (5758,'Martin Ferrero');
INSERT INTO ator VALUES (4948,'Kenneth Utt');
INSERT INTO ator VALUES (6488,'Norman Chancer');
INSERT INTO ator VALUES (3896,'Jean Speegle Howard');
INSERT INTO ator VALUES (4789,'Karen Maruyama');
INSERT INTO ator VALUES (844,'Blain Fairman');
INSERT INTO ator VALUES (764,'Bill Dalzell III');
INSERT INTO ator VALUES (100,'Brian Libby');
INSERT INTO ator VALUES (927,'Brad Dourif');
INSERT INTO ator VALUES (1001,'Brian Markinson');
INSERT INTO ator VALUES (687,'Bernard  Fox (I)');
INSERT INTO ator VALUES (769,'Bill Graham');
INSERT INTO ator VALUES (8351,'Ted Levine');
INSERT INTO ator VALUES (5921,'Mel Gibson');
INSERT INTO ator VALUES (9081,'Xander Berkeley');
INSERT INTO ator VALUES (7380,'Robert  Beatty (I)');
INSERT INTO ator VALUES (4950,'Kenny  Baker (I)');
INSERT INTO ator VALUES (8353,'Ted Markland');
INSERT INTO ator VALUES (7705,'Rudy Bond');
INSERT INTO ator VALUES (7624,'Ron Pitts');
INSERT INTO ator VALUES (7462,'Robert Krantz');
INSERT INTO ator VALUES (5923,'Mel Smith');
INSERT INTO ator VALUES (8435,'Thomas J. Hageboeck');
INSERT INTO ator VALUES (8273,'Susan Vidler');
INSERT INTO ator VALUES (7382,'Robert  Carlyle (I)');
INSERT INTO ator VALUES (5762,'Martin Jarvis');
INSERT INTO ator VALUES (6816,'Peter  Greene (I)');
INSERT INTO ator VALUES (6654,'Patrick Stewart');
INSERT INTO ator VAlueS (6736,'Paul Lazar');
INSERT INTO ator VALUES (7547,'Robin Wright');
INSERT INTO ator VALUES (6737,'Paul LeClair');
INSERT INTO ator VALUES (5684,'Mark  Thompson (II)');
INSERT INTO ator VALUES (9087,'Yaphet Kotto');
INSERT INTO ator VALUES (5847,'Matt Ross');
INSERT INTO ator VALUES (5766,'Martin Murphy');
INSERT INTO ator VALUES (5769,'Martin Serene');
INSERT INTO ator VALUES (931,'Brad Pitt');
INSERT INTO ator VALUES (692,'Bernard Hill');
INSERT INTO ator VALUES (694,'Bernard Horsfall');
INSERT INTO ator VALUES (859,'Bob  Collins (III)');
INSERT INTO ator VALUES (8601,'Tom Towles');
INSERT INTO ator VALUES (6902,'Peter Schrum');
INSERT INTO ator VALUES (6821,'Peter  Mayhew (II)');
INSERT INTO ator VALUES (6741,'Paul Mantee');
INSERT INTO ator VALUES (7633,'Ron Vawter');
INSERT INTO ator VALUES (6904,'Peter Sellers');
INSERT INTO ator VALUES (5770,'Martin Sheen');
INSERT INTO ator VALUES (7472,'Robert Loggia');
INSERT INTO ator VALUES (6906,'Peter Stormare');
INSERT INTO ator VALUES (691,'Mark Boone Jr.');
INSERT INTO ator VALUES (7717,'Rupert Vansittart');
INSERT INTO ator VALUES (6745,'Paul McCrane');
INSERT INTO ator VALUES (8366,'Tere Livrano');
INSERT INTO ator VALUES (7556,'Rocky Taylor');
INSERT INTO ator VALUES (7394,'Robert  Patrick (I)');
INSERT INTO ator VALUES (6665,'Patti Yasutake');
INSERT INTO ator VALUES (4965,'Kerry Rossall');
INSERT INTO ator VALUES (5695,'Mark Christopher Lawrence');
INSERT INTO ator VALUES (8288,'Suzy Amis');
INSERT INTO ator VALUES (6668,'Patty Raya');
INSERT INTO ator VALUES (4968,'Kevin  Allen (I)');
INSERT INTO ator VALUES (863,'Bob  Peck (I)');
INSERT INTO ator VALUES (864,'Bob Adrian');
INSERT INTO ator VALUES (1022,'Brigitte Kahn');
INSERT INTO ator VALUES (1025,'Brion James');
INSERT INTO ator VALUES (7800,'Sam Whipple');
INSERT INTO ator VALUES (8530,'Todd Hallowell');
INSERT INTO ator VALUES (8612,'Tommy Flanagan');
INSERT INTO ator VALUES (7640,'Ronald Lacey');
INSERT INTO ator VALUES (8532,'Todd Louiso');
INSERT INTO ator VALUES (6670,'Paul  Freeman (I)');
INSERT INTO ator VALUES (8616,'Tommy Lafitte');
INSERT INTO ator VALUES (6834,'Peter Brocco');
INSERT INTO ator VALUES (6754,'Paul Raczkowski');
INSERT INTO ator VALUES (6755,'Paul Reiser');
INSERT INTO ator VALUES (6674,'Paul  Maxwell (I)');
INSERT INTO ator VALUES (6593,'Pat McNamara');
INSERT INTO ator VALUES (5864,'Matthew Scurfield');
INSERT INTO ator VALUES (4973,'Kevin  Thompson (III)');
INSERT INTO ator VALUES (8538,'Tom  Mason (I)');
INSERT INTO ator VALUES (8295,'Sydney Greenstreet');
INSERT INTO ator VALUES (6837,'Peter Bull');
INSERT INTO ator VALUES (8296,'Sydney Lassick');
INSERT INTO ator VALUES (4975,'Kevin Bacon');
INSERT INTO ator VALUES (6598,'Pat Roach');
INSERT INTO ator VALUES (1110,'Buzz Kilman');
INSERT INTO ator VALUES (794,'Bill Paxton');
INSERT INTO ator VALUES (795,'Bill Pullman');
INSERT INTO ator VALUES (1113,'Byron Minns');
INSERT INTO ator VALUES (877,'Bob Gunton');
INSERT INTO ator VALUES (1033,'Bronagh Gallagher');
INSERT INTO ator VALUES (959,'Brenda Hillhouse');
INSERT INTO ator VALUES (878,'Bob Harks');
INSERT INTO ator VALUES (797,'Bill Reimbold');
INSERT INTO ator VALUES (1038,'Brooke Smith');
INSERT INTO ator VALUES (7810,'Samuel L. Jackson');
INSERT INTO ator VALUES (8621,'Tommy Thomas');
INSERT INTO ator VALUES (8382,'Terrence Evans');
INSERT INTO ator VALUES (7653,'Rosalind Ayres');
INSERT INTO ator VALUES (6924,'Phil Kelly');
INSERT INTO ator VALUES (4980,'Kevin Cooney');
INSERT INTO ator VALUES (7735,'Rutger Hauer');
INSERT INTO ator VALUES (7492,'Robert Picardo');
INSERT INTO ator VALUES (6845,'Peter Cook');
INSERT INTO ator VALUES (8548,'Tom  Wood (II)');
INSERT INTO ator VALUES (7657,'Rosanna Arquette');
INSERT INTO ator VALUES (7577,'Roger Corman');
INSERT INTO ator VALUES (6848,'Peter Crombie');
INSERT INTO ator VALUES (8388,'Terry Forrestal');
INSERT INTO ator VALUES (964,'Brendan  Kelly (I)');
INSERT INTO ator VALUES (1120,'C.J. Bau');
INSERT INTO ator VALUES (1202,'Carol Kane');
INSERT INTO ator VALUES (967,'Brendan Gleeson');
INSERT INTO ator VALUES (1045,'Bruce  Wright (I)');
INSERT INTO ator VALUES (7903,'Sean McGinley');
INSERT INTO ator VALUES (6850,'Peter Cushing');
INSERT INTO ator VALUES (8390,'Terry Gilliam');
INSERT INTO ator VALUES (6851,'Peter Dobson');
INSERT INTO ator VALUES (5960,'Michael  Bates (I)');
INSERT INTO ator VALUES (8472,'Tim Kelleher');
INSERT INTO ator VALUES (8391,'Terry Jones');
INSERT INTO ator VALUES (6690,'Paul Bartel');
INSERT INTO ator VALUES (7746,'Ryan Holihan');
INSERT INTO ator VALUES (4993,'Kevin Mangan');
INSERT INTO ator VALUES (6938,'Philip  Roth (II)');
INSERT INTO ator VALUES (8397,'Terry Richards');
INSERT INTO ator VALUES (6939,'Philip  Stone (I)');
INSERT INTO ator VALUES (970,'Brent Hinkley');
INSERT INTO ator VALUES (972,'Brent Spiner');
INSERT INTO ator VALUES (893,'Bob Penny');
INSERT INTO ator VALUES (975,'Brett Cullen');
INSERT INTO ator VALUES (1050,'Bruce Boa');
INSERT INTO ator VALUES (976,'Brett Rice');
INSERT INTO ator VALUES (1051,'Bruce Bohne');
INSERT INTO ator VALUES (977,'Brian  Cox (III)');
INSERT INTO ator VALUES (1136,'Cameron Thor');
INSERT INTO ator VALUES (1139,'Camilla Overbye Roos');
INSERT INTO ator VALUES (8720,'Tudor Sherrard');
INSERT INTO ator VALUES (7913,'Sean Young');
INSERT INTO ator VALUES (8562,'Tom Hanks');
INSERT INTO ator VALUES (8481,'Tim Robbins');
INSERT INTO ator VALUES (6861,'Peter Falk');
INSERT INTO ator VALUES (8725,'Tutte Lemkow');
INSERT INTO ator VALUES (7753,'S. Epatha Merkerson');
INSERT INTO ator VALUES (8483,'Tim Roth');
INSERT INTO ator VALUES (7592,'Rohn Thomas');
INSERT INTO ator VALUES (5892,'Max Elliott Slade');
INSERT INTO ator VALUES (7756,'Sachi Parker');
INSERT INTO ator VALUES (7676,'Ross Bagley');
INSERT INTO ator VALUES (5894,'Max Grod%nchik');
INSERT INTO ator VALUES (984,'Brian Brophy');
INSERT INTO ator VALUES (2111,'Diane Baker');
INSERT INTO ator VALUES (1222,'Carrie Fisher');
INSERT INTO ator VALUES (1060,'Bruce Kirkpatrick');
INserT INTO ator VALUES (1224,'Cary Elwes');
INSERT INTO ator VALUES (2034,'Delos V. Smith Jr.');
INSERT INTO ator VALUES (989,'Brian Delate');
INSERT INTO ator VALUES (2116,'Diane Keaton');
INSERT INTO ator VALUES (8735,'Uma Thurman');
INSERT INTO ator VALUES (6873,'Peter Kent');
INSERT INTO ator VALUES (8656,'Tony Giorgio');
INSERT INTO ator VALUES (7765,'Sally Field');
INSERT INTO ator VALUES (7767,'Sally Kinghorne');
INSERT INTO ator VALUES (6879,'Peter Lorre');
INSERT INTO ator VALUES (2040,'Denholm Elliott');
INSERT INTO ator VALUES (2121,'Diane Rodriguez');
INSERT INTO ator VALUES (1231,'Casey Siemaszko');
INSERT INTO ator VALUES (2203,'Don Fellows');
INSERT INTO ator VALUES (2204,'Don Fischer');
INSERT INTO ator VALUES (1071,'Bruce Willis');
INSERT INTO ator VALUES (2044,'Denis Lawson');
INSERT INTO ator VALUES (1155,'Carl Bressler');
INSERT INTO ator VALUES (1236,'Castulo Guerra');
INSERT INTO ator VALUES (1159,'Carl Duering');
INSERT INTO ator VALUES (7930,'Shane Rimmer');
INSERT INTO ator VALUES (7770,'Sally Wingert');
INSERT INTO ator VALUES (7933,'Shannon Wilcox');
INSERT INTO ator VALUES (8908,'Warren Clarke');
INSERT INTO ator VALUES (7937,'Sharon Anderson');
INSERT INTO ator VALUES (7856,'Sayed Badreya');
INSERT INTO ator VALUES (7775,'Sam  Anderson (I)');
INSERT INTO ator VALUES (7857,'Scatman Crothers');
INSERT INTO ator VALUES (7777,'Sam Bottoms');
INSERT INTO ator VALUES (7697,'Rozwill Young');
INSERT INTO ator VALUES (5997,'Michael Berryman');
INSERT INTO ator VALUES (5998,'Michael Biehn');
INSERT INTO ator VALUES (3100,'Glenn Beck');
INSERT INTO ator VALUES (1400,'Chris Isaak');
INSERT INTO ator VALUES (2212,'Don Lake');
INSERT INTO ator VALUES (2132,'Dick Cavett');
INSERT INTO ator VALUES (1323,'Charles Napier');
INSERT INTO ator VALUES (2052,'Denney Pierce');
INSERT INTO ator VALUES (1406,'Chris Penn');
INSERT INTO ator VALUES (2217,'Don McManus');
INSERT INTO ator VALUES (1084,'Buck Kartalian');
INSERT INTO ator VALUES (8911,'Warren Keith');
INSERT intO ator VALUES (8832,'Vincent Schiavelli');
INSERT INTO ator VALUES (6891,'Peter Mullan');
INSERT INTO ator VALUES (8838,'Ving Rhames');
INSERT INTO ator VALUES (8757,'Van Ling');
INSERT INTO ator VALUES (8597,'Tom Skerritt');
INSERT INTO ator VALUES (7788,'Sam Neill');
INSERT INTO ator VALUES (1410,'Chris Sarandon');
INSERT INTO ator VALUES (1331,'Charles Techman');
INSERT INTO ator VALUES (1413,'Christian Clemenson');
INSERT INTO ator VALUES (2304,'Douglas Rain');
INSERT INTO ator VALUES (4006,'Jeremy Sinden');
INSERT INTO ator VALUES (2146,'Dick Stilwell');
INSERT INTO ator VALUES (3118,'Gloria Stuart');
INSERT INTO ator VALUES (2229,'Don Stanton');
INSERT INTO ator VALUES (1098,'Burnell Tucker');
INSERT INTO ator VALUES (8920,'Wayne A. Evenson');
INSERT INTO ator VALUES (1099,'Burr Steers');
INSERT INTO ator VALUES (8761,'Vanessa J. Wells');
INSERT INTO ator VALUES (8680,'Tony Simotes');
INSERT INTO ator VALUES (8924,'Wayne Duvall');
INSERT INTO ator VALUES (8683,'Tony Todd');
INSERT INTO ator VALUES (8684,'Tony Vogel');
INSERT INTO ator VALUES (7874,'Scott Glenn');
INSERT INTO ator VALUES (8928,'Wayne Knight');
INSERT INTO ator VALUES (8767,'Venessia Valentino');
INSERT INTO ator VALUES (7959,'Shay Duffin');
INSERT INTO ator VALUES (2230,'Don Stark');
INSERT INTO ator VALUES (3121,'Godfrey Quigley');
INSERT INTO ator VALUES (1421,'Christine Devine');
INSERT INTO ator VALUES (3123,'Googy Gress');
INSERT INTO ator VALUES (1423,'Christine Estabrook');
INSERT INTO ator VALUES (2071,'Dennis Hopper');
INSERT INTO ator VALUES (2233,'Donal Gibson');
INSERT INTO ator VALUES (1181,'Carlos Lacamara');
INSERT INTO ator VALUES (1505,'Clair Forlani');
INSERT INTO ator VALUES (3125,'Gordon Greene');
INSERT INTO ator VALUES (1345,'Charlotte Chatton');
INSERT INTO ator VALUES (3046,'Gerald R. Molen');
INSERT INTO ator VALUES (8850,'Vito D''Ambrosio');
INSERT INTO ator VALUES (8851,'Vito Scotti');
INSERT INTO ator VALUES (8691,'Tracey Walter');
INSERT INTO ator VALUES (8935,'Wendie Jperber');
INSERT INTO ator VALUES (8857,'Vivica A. Fox');
INSERT INTO ator VALUES (7966,'Sheila Raynor');
INSERT INTO ator VALUES (8777,'Veronica Cartwright');
INSERT INTO ator VALUES (8697,'Tracy Reed');
INSERT INTO ator VALUES (7968,'Shelagh Fraser');
INSERT INTO ator VALUES (8698,'Tracy Reiner');
INSERT INTO ator VALUES (12,'Abdul Salaam El Razzac');
INSERT INTO ator VALUES (13,'Abe Vigoda');
INSERT INTO ator VALUES (4020,'Jerry Dunphy');
INSERT INTO ator VALUES (4101,'Jim Palmer');
INSERT INTO ator VALUES (4102,'Jim Piddock');
INSERT INTO ator VALUES (4103,'Jim Roche');
INSERT INTO ator VALUES (2241,'Donald Fullilove');
INSERT INTO ator VALUES (19,'Adam Baldwin');
INSERT INTO ator VALUES (2323,'Duffy Gaver');
INSERT INTO ator VALUES (3052,'Gerard G. Williams');
INSERT INTO ator VALUES (1515,'Clancy Brown');
INSERT INTO ator VALUES (3054,'Gerard McSorley');
INSERT INTO ator VALUES (3216,'Gwenda Deacon');
INSERT INTO ator VALUES (4027,'Jerry Harte');
INSERT INTO ator VALUES (3218,'Gwth Paltrow');
INSERT INTO ator VALUES (1357,'Chazz Palminteri');
INSERT INTO ator VALUES (2089,'Derek Kim');
INSERT INTO ator VALUES (1199,'Carol Cleveland');
INSERT INTO ator VALUES (8781,'Vic Tablian');
INSERT INTO ator VALUES (7892,'Sean  Sullivan (I)');
INSERT INTO ator VALUES (8946,'Wendy L. Walsh');
INSERT INTO ator VALUES (7896,'Sean Connery');
INSERT INTO ator VALUES (5000,'Kevin Pollak');
INSERT INTO ator VALUES (3301,'Harve Presnell');
INSERT INTO ator VALUES (2411,'Eddie Tagoe');
INSERT INTO ator VALUES (5003,'Kevin Sifuentes');
INSERT INTO ator VALUES (5004,'Kevin Spacey');
INSERT INTO ator VALUES (3304,'Harvey Fierstein');
INSERT INTO ator VALUES (5005,'Kevin Thigpen');
INSERT INTO ator VALUES (1280,'Charles A. Tamburro');
INSERT INTO ator VALUES (2090,'Derek Webster');
INSERT INTO ator VALUES (3144,'Graham Chapman');
INSERT INTO ator VALUES (2254,'Donald Zinn');
INSERT INTO ator VALUES (4117,'Jimmy Keogh');
INSERT INTO ator VALUES (3227,'Hal Galili');
INSERT INTO ator values (3308,'Harvey Keitel');
INSERT INTO ator VALUES (4038,'Jerry Ziesmer');
INSERT INTO ator VALUES (3067,'Giancarlo Esposito');
INSERT INTO ator VALUES (3069,'Gianni Russo');
INSERT INTO ator VALUES (8792,'Victor Garber');
INSERT INTO ator VALUES (8875,'Wallace Shawn');
INSERT INTO ator VALUES (30,'Adam Scott');
INSERT INTO ator VALUES (4201,'Joe Morton');
INSERT INTO ator VALUES (2340,'Dwight Hicks');
INSERT INTO ator VALUES (1531,'Claude Rains');
INSERT INTO ator VALUES (2341,'Dwight Marfield');
INSERT INTO ator VALUES (38,'Adelle Lutz');
INSERT INTO ator VALUES (1453,'Christopher Guest');
INSERT INTO ator VALUES (3317,'Hawthorne James');
INSERT INTO ator VALUES (3156,'Granville ''Danny'' Young');
INSERT INTO ator VALUES (2185,'Dominique Jennings');
INSERT INTO ator VALUES (1457,'Christopher John Fields');
INSERT INTO ator VALUES (2189,'Don  Henderson (II)');
INSERT INTO ator VALUES (106,'Alan Polonsky');
INSERT INTO ator VALUES (8961,'Whitby Hertford');
INSERT INTO ator VALUES (7994,'Sley Henderson');
INSERT INTO ator VALUES (5102,'Lamont Arnold');
INSERT INTO ator VALUES (45,'Adrienne Corri');
INSERT INTO ator VALUES (1621,'Courtney Gains');
INSERT INTO ator VALUES (4213,'Joe Savino');
INSERT INTO ator VALUES (47,'Afemo Omilami');
INSERT INTO ator VALUES (2432,'Edward Bunker');
INSERT INTO ator VALUES (3161,'Greg Collins');
INSERT INTO ator VALUES (1704,'Dan Stanton');
INSERT INTO ator VALUES (2433,'Edward Furlong');
INSERT INTO ator VALUES (1462,'Christopher Lloyd');
INSERT INTO ator VALUES (4216,'Joe Spano');
INSERT INTO ator VALUES (1625,'Craig  Kelly (II)');
INSERT INTO ator VALUES (1464,'Christopher Malcolm');
INSERT INTO ator VALUES (5109,'Lance Henriksen');
INSERT INTO ator VALUES (1467,'Christopher Meloni');
INSERT INTO ator VALUES (2196,'Don Blakely');
INSERT INTO ator VALUES (2358,'Earl Boen');
INSERT INTO ator VALUES (2197,'Don Brockett');
INSERT INTO ator VALUES (8971,'Will Hare');
INSERT INTO ator VALUES (8978,'Will Sampson');
INSERT INTO ator VALUES (9,'Will Smith');
INSERT INTO ator VALUES (8899,'Walter von Huene');
INSERT INTO ator VALUES (4221,'Joe Turkel');
INSERT INTO ator VALUES (6005,'Michael Burgess');
INSERT INTO ator VALUES (2441,'Edward James Olmos');
INSERT INTO ator VALUES (6006,'Michael Byrne');
INSERT INTO ator VALUES (3333,'Heidi Schanz');
INSERT INTO ator VALUES (4143,'Joanna Cassidy');
INSERT INTO ator VALUES (1634,'Crispin Glover');
INSERT INTO ator VALUES (1474,'Christopher Plummer');
INSERT INTO ator VALUES (1556,'Clint Howard');
INSERT INTO ator VALUES (1394,'Chris Ellis');
INSERT INTO ator VALUES (1639,'Cully Fredricksen');
INSERT INTO ator VALUES (1559,'Clive Merrison');
INSERT INTO ator VALUES (121,'Albert Hall');
INSERT INTO ator VALUES (1479,'Christopher Walken');
INSERT INTO ator VALUES (8983,'Willem Dafoe');
INSERT INTO ator VALUES (5200,'Lee Golden');
INSERT INTO ator VALUES (5040,'Kimberly Beck');
INSERT INTO ator VALUES (3340,'Helen Horton');
INSERT INTO ator VALUES (5203,'Lee McCain');
INSERT INTO ator VALUES (1640,'Curt Bois');
INSERT INTO ator VALUES (1560,'Clive Revill');
INSERT INTO ator VALUES (3506,'Irma St. Paule');
INSERT INTO ator VALUES (5126,'Larry Brandenburg');
INSERT INTO ator VALUES (1806,'Daryl Hannah');
INSERT INTO ator VALUES (3426,'Howard Platt');
INSERT INTO ator VALUES (5046,'Kiran Shah');
INSERT INTO ator VALUES (5208,'Lee Ross');
INSERT INTO ator VALUES (2536,'Elsa Raven');
INSERT INTO ator VALUES (5048,'Kirk Baltz');
INSERT INTO ator VALUES (2538,'Elston Ridgle');
INSERT INTO ator VALUES (4239,'Joey Perillo');
INSERT INTO ator VALUES (2377,'Ed Harris');
INSERT INTO ator VALUES (1486,'Chuck Aber');
INSERT INTO ator VALUES (210,'Alison Waddell');
INSERT INTO ator VALUES (1569,'Colette Hiller');
INSERT INTO ator VALUES (134,'Alec Guinness');
INSERT INTO ator VALUES (6100,'Michael Palin');
INSERT INTO ator VALUES (4320,'John Bennett Perry');
INSERT INTO ator VALUES (6023,'Michael Culver');
INSERT INTO ator VALUES (74,'Al Martino');
INSERT INTO ator VALUES (75,'Altthews');
INSERT INTO ator VALUES (3270,'Harris Savides');
INSERT INTO ator VALUES (5052,'Kirk Ward');
INSERT INTO ator VALUES (2705,'Frances  Fisher (I)');
INSERT INTO ator VALUES (77,'Al Pacino');
INSERT INTO ator VALUES (3272,'Harrison Ford');
INSERT INTO ator VALUES (6108,'Michael Reid MacKay');
INSERT INTO ator VALUES (3192,'Gregory Sporleder');
INSERT INTO ator VALUES (4164,'Jodie Foster');
INSERT INTO ator VALUES (4407,'John Horton');
INSERT INTO ator VALUES (1574,'Colin Firth');
INSERT INTO ator VALUES (2547,'Emily Ann Lloyd');
INSERT INTO ator VALUES (3519,'Ishaq Bux');
INSERT INTO ator VALUES (4168,'Joe Alaskey');
INSERT INTO ator VALUES (220,'Allan Kolman');
INSERT INTO ator VALUES (146,'Alex Coleman');
INSERT INTO ator VALUES (5220,'Leib Lensky');
INSERT INTO ator VALUES (6031,'Michael Dorn');
INSERT INTO ator VALUES (2710,'Frances McDormand');
INSERT INTO ator VALUES (4411,'John Hurt');
INSERT INTO ator VALUES (4331,'John C. McGinley');
INSERT INTO ator VALUES (3603,'Jack holson');
INSERT INTO ator VALUES (7006,'Quentin Tarantino');
INSERT INTO ator VALUES (1822,'David  Andrews (I)');
INSERT INTO ator VALUES (5305,'Liisa Repo-Martell');
INSERT INTO ator VALUES (1580,'Colleen Camp');
INSERT INTO ator VALUES (3443,'Hugh Ross');
INSERT INTO ator VALUES (1824,'David  Brisbin (I)');
INSERT INTO ator VALUES (4335,'John Capodice');
INSERT INTO ator VALUES (6037,'Michael Ensign');
INSERT INTO ator VALUES (3526,'Ivy Bethune');
INSERT INTO ator VALUES (5227,'Leland Orser');
INSERT INTO ator VALUES (2555,'Endre Hules');
INSERT INTO ator VALUES (3284,'Harry Connick Jr.');
INSERT INTO ator VALUES (4337,'John Carroll Lynch');
INSERT INTO ator VALUES (4418,'John Kavanagh');
INSERT INTO ator VALUES (2718,'Franco Citti');
INSERT INTO ator VALUES (2475,'Eleanor Clift');
INSERT INTO ator VALUES (3285,'Harry Dean Stanton');
INSERT INTO ator VALUES (3528,'Jrgen Prochnow');
INSERT INTO ator VALUES (3609,'Jack Purvis');
INSERT INTO ator VALUES (5067,'Kristin Scott Thomas');
INSERT INTO ator VALUES (2557,'Ennalls Berl');
INSERT INTO ator VALUES (3448,'Humphrey Bogart');
INSERT INTO ator VALUES (1748,'Daniel Zacapa');
INSERT INTO ator VALUES (1586,'Connie Booth');
INSERT INTO ator VALUES (4097,'Jim Meskimen');
INSERT INTO ator VALUES (1749,'Daniel von Bargen');
INSERT INTO ator VALUES (156,'Alex Norton');
INSERT INTO ator VALUES (157,'Alex Rocco');
INSERT INTO ator VALUES (7010,'R. Lee Ermey');
INSERT INTO ator VALUES (6201,'Mike Jolly');
INSERT INTO ator VALUES (3611,'Jack Shearer');
INSERT INTO ator VALUES (4340,'John Cassini');
INSERT INTO ator VALUES (6123,'Michael Sheard');
INSERT INTO ator VALUES (4341,'John Cazale');
INSERT INTO ator VALUES (4422,'John Laughlin');
INSERT INTO ator VALUES (3613,'Jack Thibeau');
INSERT INTO ator VALUES (5233,'Lennie Loftin');
INSERT INTO ator VALUES (4424,'John Lees');
INSERT INTO ator VALUES (5154,'Laura Dern');
INSERT INTO ator VALUES (5235,'Lenny Montana');
INSERT INTO ator VALUES (6208,'Mike Muscat');
INSERT INTO ator values (6127,'Michael Sottile');
INSERT INTO ator VALUES (2563,'Eric Braeden');
INSERT INTO ator VALUES (4345,'John Cleese');
INSERT INTO ator VALUES (2726,'Frank  Marshall (I)');
INSERT INTO ator VALUES (2645,'Ewan McGregor');
INSERT INTO ator VALUES (3455,'Ian Bannen');
INSERT INTO ator VALUES (4184,'Joe Fowler');
INSERT INTO ator VALUES (4265,'John  Hollis (I)');
INSERT INTO ator VALUES (4346,'John Clive');
INSERT INTO ator VALUES (4508,'John Short');
INSERT INTO ator VALUES (2727,'Frank  Miller (I)');
INSERT INTO ator VALUES (2646,'Ewan Stewart');
INSERT INTO ator VALUES (3294,'Harry Northup');
INSERT INTO ator VALUES (2647,'Ewen Bremner');
INSERT INTO ator VALUES (1837,'David  Morse (I)');
INSERT INTO ator VALUES (2567,'Eric Clark');
INSERT INTO ator VALUES (1838,'David  Pressman (I)');
INSERT INTO ator VALUES (3297,'Harry Waters Jr.');
INSERT INTO ator VALUES (244,'Alonzo Brown');
INSERT INTO ator VALUES (406,'Anne Fletcher');
INSERT INTO ator VALUES (246,'Alun Armstrong');
INSERT INTO ator VALUES (7100,'Ray McKinnon');
INSERT INTO ator VALUES (4510,'John Spencer');
INSERT INTO ator VALUES (7022,'Rachel Schadt');
INSERT INTO ator VALUES (3703,'James Duval');
INSERT INTO ator VALUES (5161,'Laura Lovelace');
INSERT INTO ator VALUES (5323,'Linda Hamilton');
INSERT INTO ator VALUES (2570,'Eric Idle');
INSERT INTO ator VALUES (1841,'David  Warner (I)');
INSERT INTO ator VALUES (3704,'James Earl Jones');
INSERT INTO ator VALUES (6216,'Miko Hughes');
INSERT INTO ator VALUES (6054,'Michael Gover');
INSERT INTO ator VALUES (3462,'Ian Holm');
INSERT INTO ator VALUES (3463,'Ian Liston');
INSERT INTO ator VALUES (4435,'John M. Mathews');
INSERT INTO ator VALUES (4516,'John Storey');
INSERT INTO ator VALUES (2816,'Frederic Forrest');
INSERT INTO ator VALUES (1763,'Danny Darst');
INSERT INTO ator VALUES (1682,'Damien Leake');
INSERT INTO ator VALUES (2817,'Frederic W. Barnes');
INSERT INTO ator VALUES (1764,'Danny DeVito');
INSERT INTO ator VALUES (5328,'Linda Kaye');
INSERT INTO ATor VALUES (3547,'J.J. Cohen');
INSERT INTO ator VALUES (5329,'Linda Kerns');
INSERT INTO ator VALUES (4278,'John  McLaughlin (I)');
INSERT INTO ator VALUES (5169,'Lauren Roselli');
INSERT INTO ator VALUES (257,'Amanda Plummer');
INSERT INTO ator VALUES (258,'Amanda Walker');
INSERT INTO ator VALUES (7112,'Raymond Coulthard');
INSERT INTO ator VALUES (6140,'Michael Winther');
INSERT INTO ator VALUES (4520,'John Travolta');
INSERT INTO ator VALUES (2820,'Frederick Strother');
INSERT INTO ator VALUES (2740,'Frank Cavestani');
INSERT INTO ator VALUES (4441,'John Marley');
INSERT INTO ator VALUES (2903,'Gary Lee Davis');
INSERT INTO ator VALUES (1932,'David Proval');
INSERT INTO ator VALUES (1851,'David Bowe');
INSERT INTO ator VALUES (4281,'John  Morton (I)');
INSERT INTO ator VALUES (7117,'Raymond O''Connor');
INSERT INTO ator VALUES (2581,'Eric Stoltz');
INSERT INTO ator VALUES (1933,'David Prowse');
INSERT INTO ator VALUES (5173,'Laurence Fishburne');
INSERT INTO ator VALUES (6065,'MichaJ. Fox');
INSERT INTO ator VALUES (4526,'John Voldstad');
INSERT INTO ator VALUES (1692,'Dan Butler');
INSERT INTO ator VALUES (4527,'John Walcutt');
INSERT INTO ator VALUES (6068,'Michael Jace');
INSERT INTO ator VALUES (1776,'Danny Nucci');
INSERT INTO ator VALUES (1695,'Dan Hedaya');
INSERT INTO ator VALUES (5259,'Leonard Rossiter');
INSERT INTO ator VALUES (2588,'Erik Holland');
INSERT INTO ator VALUES (1697,'Dan Lauria');
INSERT INTO ator VALUES (503,'Ariana Richards');
INSERT INTO ator VALUES (261,'Amber Waddell');
INSERT INTO ator VALUES (180,'Alexis Arquette');
INSERT INTO ator VALUES (424,'Annette Helde');
INSERT INTO ator VALUES (427,'Annie Golden');
INSERT INTO ator VALUES (184,'Alfonso Freeman');
INSERT INTO ator VALUES (185,'Alfre Woodard');
INSERT INTO ator VALUES (189,'Alfred Molina');
INSERT INTO ator VALUES (8011,'Sigourney Weaver');
INSERT INTO ator VALUES (6310,'Mykelti Williamson');
INSERT INTO ator VALUES (5501,'M. Emmet Walsh');
INSERT INTO ator VALUES (7203,'Rich Attenborough');
INSERT INTO ator VALUES (7122,'Read Morgan');
INSERT INTO ator VALUES (2911,'Gary Riley');
INSERT INTO ator VALUES (4612,'Josef Pilato');
INSERT INTO ator VALUES (8015,'Simon  Jones (I)');
INSERT INTO ator VALUES (7043,'Ralph Fiennes');
INSERT INTO ator VALUES (3722,'James Hong');
INSERT INTO ator VALUES (4370,'John Dullaghan');
INSERT INTO ator VALUES (2913,'Gary Sinise');
INSERT INTO ator VALUES (2751,'Frank Gorshin');
INSERT INTO ator VALUES (1941,'David S. Lomax');
INSERT INTO ator VALUES (3561,'Jack  Ford (III)');
INSERT INTO ator VALUES (3804,'Jane Jenkins');
INSERT INTO ator VALUES (5181,'Lawrence Bender');
INSERT INTO ator VALUES (3563,'Jack  McKenzie (I)');
INSERT INTO ator VALUES (4373,'John Enos');
INSERT INTO ator VALUES (1782,'Dant% McCarthy');
INSERT INTO ator VALUES (3564,'Jack  Moore (IV)');
INSERT INTO ator VALUES (2917,'Gates McFadden');
INSERT INTO ator VALUES (3727,'James Kisicki');
INSERT INTO ator VALUES (5185,'Lawrence T. Wrentz');
INSERT INTO ator vALUES (5266,'Leonardo DiCaprio');
INSERT INTO ator VALUES (5186,'Lawrence Tierney');
INSERT INTO ator VALUES (5267,'Leonid Kinskey');
INSERT INTO ator VALUES (5348,'Lisa Freeman');
INSERT INTO ator VALUES (4297,'John  Young (I)');
INSERT INTO ator VALUES (2759,'Frank Medrano');
INSERT INTO ator VALUES (2679,'Finlay Welsh');
INSERT INTO ator VALUES (3489,'Ingo Neuhaus');
INSERT INTO ator VALUES (515,'Arnold Schwarzenegger');
INSERT INTO ator VALUES (355,'Angus MacInnes');

