algoritmo "semnome"
// Função :
// Autor :
// Data : 09/05/2013
// Seção de Declarações

Arquivo "C:\Users\Athauan Marques\Desktop\ADS\Algoritmos-Class\Dados\conta.txt"

var
cc, nome: caracter
Saldo: Real
i: inteiro

inicio
// Seção de Comandos

Para i de 1 ate 5 faca
   Escreval ("Conta-Corrente: ")
   leia (cc)

   Escreval ("nome: ")
   leia (nome)

   Escreval ("saldo: ")
   leia (Saldo)

   Escreval ("---------------------------------")
   
   fimpara
fimalgoritmo
