algoritmo "exercicio 5"
// Autor : Raul Bolsonaro Santos (Corrigido Por Panhan)
// Data : 12/03/2013
//bloco de declarações de Variáveis
var
    precoFabrica, custoConsumidor: Real


inicio
// Seção de Comandos
//Entrada de Dados

       escreva ("Informe o Preço de Fabrica ")
       leia (precoFabrica)

//Processamento

       custoConsumidor <- precoFabrica * 1.45 *1.28
       
//Saída de Dados
        EscrevA ("O custo ao Consumidor é  ", custoConsumidor)


fimalgoritmo
