algoritmo "Exercicio 1 vetor"
// Função :
// Autor :
// Data : 11/04/2013
// Seção de Declarações 
var
 A, B: vetor [1..10] de inteiro
 posicao: inteiro

inicio
// Seção de Comandos 
   para posicao de 1 ate 10 faca
     escreval("informe valor ", posicao, ": ")
     leia (A[posicao])
     
     se (posicaov% 2 = 0) entao
     B[posicao] <- A[posicao] + 5
     Senao
     B[posicao] <- A[posicao] + 5
     fimse
   Fimpara
   
   Para posicao de 1 ate 5
     
     
fimalgoritmo
