algoritmo "semnome"
// Função :
// Autor :
// Data : 14/04/2013
// Seção de Declarações 
var
 indice: real

inicio
// Seção de Comandos 

   Escreval ("Informe o indice de poluiçao: ")
   leia(indice)

   Se indice>= 0.26 entao
   Escreval ("Grupo 1 suspendem sua atividade")
   
   Se indice>= 0.31 entao
   Escreval ("Grupo do 1º e 2º suspendem suas atividades")
   
   Se indice>= 0.41 entao
   Escreval ("Todos os Grupos suspendem suas atividades")
   
   Fimse
fimalgoritmo fimse



