algoritmo "exerc4"
// Função : fazer soma
// Autor :
// Data : 12/03/2013
// Seção de Declarações 
var
nome :caracter
salarioatual, valorreajuste, salnovo: real
inicio
// entrada de dados
escreva ("Infome o seu nome: ")
leia (nome)
escreva ("Informe o salario atual: ")
leia (salarioatual)

//processamento de dados
valorreajuste <- salarioatual*0.15

salnovo <- salarioatual+valorreajuste

//saida de dados
escreva (nome," Seu salario é: ", salnovo)



fimalgoritmo
