algoritmo "semnome"
// Função :
// Autor :
// Data : 12/03/2013
// Seção de Declarações 
var
n1,n2,soma,produto,quociente :real
inicio
// Seção de Comandos 
escreva ("Informe n1: ")
leia(n1)
escreva ("informe n2: ")
leia (n2)

Soma <- n1+n2
produto <-n1*n2
quociente <-n1/n2

Escreval ("Resultado da soma é: ", soma)
Escreval("Resulatado do produto é: ", produto)
Escreval ("Resultado do quociente é: ", quociente)
fimalgoritmo
