algoritmo "semnome"
// Função :
// Autor :
// Data : 09/07/2013
// Seção de Declarações 
var
P, excesso, M: real
inicio
// Seção de Comandos
escreva ("Informe o peso do peixo: ")
leia (P)

se (P>50) entao
excesso <- P
M <- excesso*4
escreval
escreval ("o excesso do peso foi: ", excesso)
escreval ("o valor da multa foi: ", M)
senao
escreval
escreval ("o excesso do peso foi: ", excesso)
escreval ("o valor da multa foi: ", M)
fimse

fimalgoritmo
