algoritmo "semnome"
// Função :
// Autor :
// Data : 16/07/2013
// Seção de Declarações 
var
menor, maior, n, media: real
inicio
// Seção de Comandos
n <- 1
 enquanto (n<>500) faca

 se (n>=maior) entao
 escreval("o numero maior é : ", maior)
  se (n<=maior) entao
  menor <-maior
  escreval ("o numero menor é : ", menor)
   fimse
    fimse
Media <- n*n/n
fimenquanto
escreval("A media é : ", Media)
 





fimalgoritmo
